### PR TITLE
pruntime: separate sgx signing stage

### PR DESCRIPTION
**Pull request by jasl**
This refactor for standalone Pink build Docker image,
The image will make the PRuntime, and we shall push it to Dockerhub or somewhere to let people examine it.

But we won't expose our signing info which is useless for reproducible, and it's confidential.

NOTE:
Usually, `cargo build --release -p pink` should be enough to build `pink`, but I found this always making the pink recompile, and I realize unlike the standard SGX SDK toolchain, there is no promise for crates reproducible.

So instead of building PInk only, I compile the whole PRuntime, and its Makefile will prevent `libpink.so` recompile.

We should consider how to ensure it's reproducible, and I remember Parity has a tool called SRtools.

The Dockerfile: https://github.com/Phala-Network/phala-docker/blob/gramine/pink-builder.Dockerfile

### CODE REVIEW

**Comment by kvinwang** [comment]
> So instead of building PInk only, I compile the whole PRuntime, and its Makefile will prevent `libpink.so` recompile.

Why do we care about the recompile of libpink.so?
Does it mean even if we provide a docker image with the toolchains installed, we still can not build reproducable libpink.so and pruntime with it?

**Comment by kvinwang** [comment]
> Usually, `cargo build --release -p pink` should be enough to build `pink`, but I found this always making the pink recompile, and I realize unlike the standard SGX SDK toolchain, there is no promise for crates reproducible.

[Here](https://github.com/rust-lang/rust/labels/A-reproducibility)'s a list of issues about the reproduceable build for Rustc.
Almost all of them are the build environment changes caused problem. So can we assuming that the output of rustc is already reproducable if we make sure the build environments are identical?

**Comment by jasl** [comment]
> > So instead of building PInk only, I compile the whole PRuntime, and its Makefile will prevent `libpink.so` recompile.
> 
> The libpink.so and pruntime will always recompile on purpose because the build.rs will always rerun to read the git commit hash. See [here](https://github.com/Phala-Network/phala-blockchain/blob/master/crates/phala-git-revision/build.rs#L41). This behavier shouldn't be relevant to reproducable.
> 
> Why do we care about the recompile of libpink.so? Does it mean even if we provide a docker image with the toolchains installed, we still can not build reproducable libpink.so and pruntime with it?

I would love to avoid recompiling. The expected workflow are:
- we build the Docker image and upload
- extract `libpink.so` from the Docker image

Avoiding recompiling would help to avoid changing the build artifacts accidentally, like a wrong act to rebuild the project.
I know the recompiling is because of reading the git commit. However, recompiling is still considered dangerous that may change the result.

**Comment by jasl** [comment]
> > Usually, `cargo build --release -p pink` should be enough to build `pink`, but I found this always making the pink recompile, and I realize unlike the standard SGX SDK toolchain, there is no promise for crates reproducible.
> 
> [Here](https://github.com/rust-lang/rust/labels/A-reproducibility)'s a list of issues about the reproduceable build for Rustc. Almost all of them are the build environment changes caused problem. So can we assuming that the output of rustc is already reproducable if we make sure the build environments are identical?

Yes, I hope in the next step we can minify the built environment, and explicit declare versions

**Comment by kvinwang** [comment]
> I would love to avoid recompiling. The expected workflow are:
> 
> * we build the Docker image and upload
> * extract `libpink.so` from the Docker image

I don't fully understand this workflow. Isn't the purpose of the [pink-builder.Dockerfile](https://github.com/Phala-Network/phala-docker/blob/gramine/pink-builder.Dockerfile) to compile a `libpink.so`? If it just copy a prebuild one, why do we need it?
In my mind, if someone concerns about the prebuilt `libpink.so`, we can tell him: "Trust me, It was compile from the `pink-builder.Dockerfile`. You can try to compile it yourself and get the same result.". If the Dockerfile serves on this purpose, it should always recompile.

**Comment by kvinwang** [comment]
> Avoiding recompiling would help to avoid changing the build artifacts accidentally, like a wrong act to rebuild the project.

Maybe a full pruntime release workflow steps can help me understand it.

**Comment by jasl** [comment]
> > I would love to avoid recompiling. The expected workflow are:
> > 
> > * we build the Docker image and upload
> > * extract `libpink.so` from the Docker image
> 
> I don't fully understand this workflow. Isn't the purpose of the [pink-builder.Dockerfile](https://github.com/Phala-Network/phala-docker/blob/gramine/pink-builder.Dockerfile) to compile a `libpink.so`? If it just copy a prebuild one, why do we need it? In my mind, if someone concerns about the prebuilt `libpink.so`, we can tell him: "Trust me, It was compile from the `pink-builder.Dockerfile`. You can try to compile it yourself and get the same result.". If the Dockerfile serves on this purpose, it should always recompile.

I don't have a preference for this. Run `cargo build --release -p pink` also looks good.

In my understanding, PRuntime and PInk have separate releasing cycles, so when we are ready to release new Pink, we use the Dockerfile to build an image and extract the `libpink.so` to PRuntime repo.
When we release PRuntime, we still use the current process.

**Review by kvinwang — APPROVED** [review]

**Pull request merged**
