### PR TITLE
Move JS-SDK into the main repository for better collaboration

### PR DESCRIPTION
**Pull request by lucasliu2022**
add js sdk to this repo

### CODE REVIEW

**Comment by Leechael** [comment]
lgtm.

**Review by Leechael — APPROVED** [review]

**Comment by h4x3rotab** [comment]
Do we intend to put node_modules into the repo? Why?

**Review by Leechael — COMMENTED** [review]
Does `sdk/dist` can move out from repository as well? Since we can build sdk before run e2e script.

**Comment by Leechael** [comment]
@h4x3rotab When this PR is ready, I suggest using "squash and merge" for this case (getting more meaningful commit when we need tracking back).

**Comment by h4x3rotab** [comment]
OK. I will wait for your approval. @Leechael

**Pull request closed without merging**
