### PR TITLE
sidevm-host: Add http api to push messages to guest program.

### PR DESCRIPTION
**Pull request by kvinwang**
For better debug experience.

Usage: 
```bash
ROCKET_PORT=8003 sidevm-host path/to/the/sideprog.wasm&

curl -d hello localhost:8003/push/message
```

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Could you add a `README.md` to the sidevm-host project?

**Comment by kvinwang** [comment]
> Could you add a `README.md` to the sidevm-host project?

Added

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Comment by h4x3rotab** [comment]
@Soptq FYI

**Pull request merged**
