### PR TITLE
Simplify get_info_json && add /info

### PR DESCRIPTION
**Pull request by kvinwang**
Difference between `/info` and `/get_info`:

/get_info
```bash
$ curl localhost:8000/get_info
{"payload":"{\"blocknum\":6,\"dev_mode\":true,\"ecdh_public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d\",\"gatekeeper\":{\"master_public_key\":\"\",\"role\":0},\"genesis_block_hash\":\"ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55\",\"git_revision\":\"8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty\",\"headernum\":6,\"initialized\":true,\"memory_usage\":{\"rust_peak_used\":7447633,\"rust_used\":1733183,\"total_peak_used\":8404076},\"network_status\":{\"config\":null,\"public_rpc_port\":null},\"number_of_clusters\":0,\"number_of_contracts\":0,\"para_headernum\":0,\"pending_messages\":1,\"public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d\",\"registered\":true,\"running_side_tasks\":0,\"score\":0,\"state_root\":\"67a811551243f0eae21165f25c4aaa3a8c281cb8dea9925980194eba286e6a09\",\"version\":\"2.0.0\",\"waiting_for_paraheaders\":false}","signature":"7677b6b888f6b02f8e084bdbc8d4af42b7eaf0070dc45e09c3b404edf28882629bdfee3b4d7978d5eaf1831aafb1dd1ce17a0751c33082cb0db9d38d7133498a","status":"ok"}

$ curl localhost:8000/get_info | jq
{
  "payload": "{\"blocknum\":9,\"dev_mode\":true,\"ecdh_public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d\",\"gatekeeper\":{\"master_public_key\":\"\",\"role\":0},\"genesis_block_hash\":\"ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55\",\"git_revision\":\"8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty\",\"headernum\":9,\"initialized\":true,\"memory_usage\":{\"rust_peak_used\":7447633,\"rust_used\":1733255,\"total_peak_used\":8404076},\"network_status\":{\"config\":null,\"public_rpc_port\":null},\"number_of_clusters\":0,\"number_of_contracts\":0,\"para_headernum\":0,\"pending_messages\":0,\"public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d\",\"registered\":true,\"running_side_tasks\":0,\"score\":0,\"state_root\":\"c4d5264ad14f08f1b20c44dba5044c9c4aa160d680134f259f4e8dd1de182ada\",\"version\":\"2.0.0\",\"waiting_for_paraheaders\":false}",
  "signature": "7ab51f7c629ca3d8367b96af0cf3712d222065ffd6eeb9bc4908b17c7210157244d7f37b626e2da1e78fd57fa8ea9a4fff91645c64da2df64a688d31b8b5c680",
  "status": "ok"
}


$ curl localhost:8000/get_info | jq .payload -r
{"blocknum":17,"dev_mode":true,"ecdh_public_key":"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d","gatekeeper":{"master_public_key":"","role":0},"genesis_block_hash":"ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55","git_revision":"8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty","headernum":17,"initialized":true,"memory_usage":{"rust_peak_used":7447633,"rust_used":1745915,"total_peak_used":8404076},"network_status":{"config":null,"public_rpc_port":null},"number_of_clusters":0,"number_of_contracts":0,"para_headernum":0,"pending_messages":0,"public_key":"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d","registered":true,"running_side_tasks":0,"score":0,"state_root":"2dfca709115019062fbb44d03767f4430ec459f42af5299e23695d39e5129966","version":"2.0.0","waiting_for_paraheaders":false}

$ curl localhost:8000/get_info | jq .payload -r | jq
{
  "blocknum": 16,
  "dev_mode": true,
  "ecdh_public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
  "gatekeeper": {
    "master_public_key": "",
    "role": 0
  },
  "genesis_block_hash": "ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55",
  "git_revision": "8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty",
  "headernum": 16,
  "initialized": true,
  "memory_usage": {
    "rust_peak_used": 7447633,
    "rust_used": 1743476,
    "total_peak_used": 8404076
  },
  "network_status": {
    "config": null,
    "public_rpc_port": null
  },
  "number_of_clusters": 0,
  "number_of_contracts": 0,
  "para_headernum": 0,
  "pending_messages": 0,
  "public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
  "registered": true,
  "running_side_tasks": 0,
  "score": 0,
  "state_root": "6faf8ecf9175ff705f8a5146a9dc0363c95e3135903418c03b7f55cd9d82860f",
  "version": "2.0.0",
  "waiting_for_paraheaders": false
}
```

/info
```bash
curl localhost:8000/info
{
  "initialized": true,
  "registered": true,
  "genesis_block_hash": "ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55",
  "public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
  "ecdh_public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
  "headernum": 19,
  "para_headernum": 0,
  "blocknum": 19,
  "state_root": "2c88c29bbfb99c7480a60f968a2f3094ba36238d58b5c793c98b7e64a6b347a2",
  "dev_mode": true,
  "pending_messages": 0,
  "score": 0,
  "gatekeeper": {
    "role": 0,
    "master_public_key": ""
  },
  "version": "2.0.0",
  "git_revision": "8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty",
  "running_side_tasks": 0,
  "memory_usage": {
    "rust_used": 1739202,
    "rust_peak_used": 7447633,
    "total_peak_used": 8404076
  },
  "number_of_clusters": 0,
  "number_of_contracts": 0,
  "waiting_for_paraheaders": false,
  "network_status": {
    "public_rpc_port": null,
    "config": null
  }
}
```

### CODE REVIEW

**Comment by h4x3rotab** [comment]
I wonder how the grpc reply was signed now...

**Comment by kvinwang** [comment]
> I wonder how the grpc reply was signed now...

No signature in prpc response


> do you think it's easier to just put the signature in the response http header rather at the application level?

Sounds good

**Comment by h4x3rotab** [comment]
Signing takes time. Maybe we can by default add the signature for the public rpc port, and make an option for the client to request for signature by adding a request header

**Comment by h4x3rotab** [comment]
What do we do with this PR? Will it be removed since we have #971?

**Comment by kvinwang** [comment]
> What do we do with this PR? Will it be removed since we have #971?

This PR doesn't conflict with  #971.  #971 Add signature for public RPC. 
This PR refactors code style and added a convenient `/info` for dev and devops.

**Comment by h4x3rotab** [comment]
OK

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Pull request merged**
